\documentclass[12pt]{article}
\usepackage{geometry}                % See geometry.pdf to learn the layout options. There are lots.
\geometry{letterpaper}                   % ... or a4paper or a5paper or ... 
%\geometry{landscape}                % Activate for for rotated page geometry
\usepackage[parfill]{parskip}    % Activate to begin paragraphs with an empty line rather than an indent
\usepackage{graphicx}
\usepackage{amssymb}
\usepackage{amsthm}
\usepackage{subfig}

\newtheorem{model}{Data-Generating Model}


\title{MCMC inference for qPCR quantitation via branching processes}
\author{Wesley Brooks}
\date{}                                           % Activate to display a given date or no date

\begin{document}
\SweaveOpts{concordance=TRUE}
\setkeys{Gin}{width=0.9\textwidth}    %make figures a bit wider than the Sweave default.
\maketitle

    
\section{Overview}
Bret: because you are quite familiar with may project and its background, I will dispense with some formality in the presentation and get right to the results and discussion.\\

In this project, I use the method presented in \cite{norway:2010} to do inference for a qPCR experiment. The dataset I'll analyze was originally presented in \cite{hanlon:2012}. The experiment was designed as for benchmarking - a cDNA sample was diluted by a factor of 3 and botht the original sample and the diluted sample were run through a qPCR machine. Ideally, our data analysis should recover the known dilution factor. When introducing their analytic method, \cite{norway:2010} used two experiments to justify their results: one was a simulation study and the other an experimental study. But because the experimental study was not controlled in the way I've described above, it was not possible to compare their presented results to a known 'true' dilution.\\

The data analysis is done via Markov Chain Monte Carlo (MCMC) under the model presented in \cite{norway:2010}. That model is:\\

Data: $Y_{ij}$ are observed fluorescence intensities which are modeled as an underlying fluorescence $X_{ij}$ plus additive noise:
\[
    Y_{ij} \sim \text{Normal}(X_{ij}, \tau_y)
\]



\section{Scope of the project}




\bibliographystyle{plain}
\bibliography{../references/qpcr}

\end{document}

